#!/bin/sh

#Mount things needed by this script
mount -t proc proc /proc
mount -t sysfs sysfs /sys

#Disable kernel messages from popping onto the screen
echo 0 > /proc/sys/kernel/printk

#Clear the screen
#clear

#Create all the symlinks to /bin/busybox
#busybox --install -s

#Create device nodes
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s

#mkdir /dev/pts
#mount -t devpts devpts /dev/pts

#Function for parsing command line options with "=" in them
# get_opt("init=/sbin/init") will return "/sbin/init"
get_opt() {
	echo "$@" | cut -d "=" -f 2
}

#Defaults
#init="/sbin/init"
#root="/dev/hda1"

#Process command line options
for i in $(cat /proc/cmdline); do
	case $i in
		root\=*)
			root=$(get_opt $i)
			;;
		init\=*)
			init=$(get_opt $i)
			;;
	esac
done

mkdir /dev/pts
mount -t devpts devpts /dev/pts

exec setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
#exec setsid cttyhack sh
#exec sh
